/// The package's own texts, so a host needs no copy of them. A host changes
/// any of them through `DefaultChatLocalizationProvider(overrides: ...)`.
///
/// Nothing here names a host's business: a topic's prompt fields are
/// labelled by the host (its `label`), or by a host override `field_<key>`.
const Map<String, Map<String, String>> chatStrings = {
  'en': {
    // Room
    'inputHint': 'Type a message',
    'slideToCancel': 'Slide to cancel',
    'releaseToCancel': 'Release to cancel',
    'errorLabel': 'Error',
    'cancelButton': 'Cancel',
    'applyButton': 'Apply',
    'clearButton': 'Clear',
    'settingsButton': 'Settings',
    'deleteMessage': 'Delete Message',
    'deleteMessageError': 'Error deleting message',
    'copyMessage': 'Copy Message',
    'copyMessageSuccess': 'Copied',
    'copyMessageSuccessMessage': 'Message copied to the clipboard',
    'copyMessageError': 'Copy Error',
    'copyMessageErrorMessage': "Message couldn't be copied",
    'downloadAttachment': 'Download',
    'playVideo': 'Play',
    'openInMaps': 'Open in Maps',
    'deleteAttachment': 'Delete',
    'micPermissionRequired': 'Permission Required',
    'micPermissionRequiredMessage': 'Microphone permission is required to send voice messages',
    'micPermissionDenied': 'Permission Denied',
    'micPermissionDeniedMessage': 'Microphone permission is permanently denied. Please enable it in app settings to use voice recording.',
    'micPermissionRestricted': 'Permission Restricted',
    'micPermissionRestrictedMessage': 'Microphone access is restricted on this device.',
    'micPermissionError': 'Error',
    'micPermissionErrorMessage': 'Failed to request microphone permission',
    // Info page
    'channelInfoTitle': 'Channel Information',
    'channelName': 'Channel Name',
    'channelId': 'Channel ID',
    'userInfoTitle': 'Your Information',
    'userId': 'Your ID',
    'userName': 'Your Name',
    'actionsTitle': 'Actions',
    'changeThemeMenuItem': 'Change Chat Theme',
    'chatThemeDialogTitle': 'Change Chat Theme',
    'chatThemeRed': 'Red Theme',
    'chatThemeBlue': 'Blue Theme',
    'chatThemeGreen': 'Green Theme',
    'clearCacheMenuTitle': 'Clear Cache & Downloads',
    'clearCacheDialogTitle': 'Clear Cache & Downloads',
    'clearCacheDialogContent': 'This will delete all cached audio files and downloaded files. This action cannot be undone.',
    'cacheCleared': 'Cache Cleared',
    'cacheClaredMessage': 'Audio cache and downloaded files have been removed',
    'clearCacheError': 'Error',
    'clearCacheErrorPrefix': 'Failed to clear cache: ',
    // Shared content
    'media': 'Media',
    'files': 'Files',
    'members': 'Members',
    'loadOlder': 'Load older messages',
    'noMedia': 'No photos or videos yet',
    'noFiles': 'No files yet',
    'noMembers': 'No members to show',
    'you': 'You',
    // Starting a chat
    'title': 'Chat',
    'conversations': 'Chats',
    'newChat': 'New chat',
    'noConversations': 'No chats yet',
    'chooseTopic': 'What is your chat about?',
    'noTopics': 'No chat topics are available.',
    'confirmStart': 'Start a chat? Everyone in it will be notified.',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'openFailed': 'Could not open the chat. Please try again.',
    'whichOne': 'Tell us which one',
    'or': 'OR',
    'find': 'Find',
    'noMatch': 'Nothing found. Please check what you entered.',
    'pickOne': 'Which one?',
    'fillOneGroup': 'Please fill in one of the options.',
  },
  'km': {
    'inputHint': 'សរសេរសារ',
    'slideToCancel': 'អូសទាញដើម្បីបោះបង់',
    'releaseToCancel': 'ដោះលែងដើម្បីបោះបង់',
    'errorLabel': 'កំហុស',
    'cancelButton': 'បោះបង់',
    'applyButton': 'អនុវត្ត',
    'clearButton': 'លុបចេញ',
    'settingsButton': 'ការកំណត់',
    'deleteMessage': 'លុបសារ',
    'deleteMessageError': 'មិនអាចលុបសារបានទេ',
    'copyMessage': 'ចម្លងសារ',
    'copyMessageSuccess': 'ចម្លងជោគជ័យ',
    'copyMessageSuccessMessage': 'សារត្រូវបានចម្លងដោយជោគជ័យ',
    'copyMessageError': 'ចម្លងបរាជ័យ',
    'copyMessageErrorMessage': 'មានបញ្ហាក្នុងការចម្លងសារ',
    'downloadAttachment': 'ទាញយក',
    'playVideo': 'លេង',
    'openInMaps': 'បើកក្នុងផែនទី',
    'deleteAttachment': 'លុបចោល',
    'micPermissionRequired': 'តម្រូវការការអនុញ្ញាត',
    'micPermissionRequiredMessage': 'ត្រូវការការអនុញ្ញាតមីក្រូហ្វូនដើម្បីផ្ញើសារជាសម្លេង',
    'micPermissionDenied': 'ការអនុញ្ញាតត្រូវបានបដិសេធ',
    'micPermissionDeniedMessage': 'ការអនុញ្ញាតមីក្រូហ្វូនត្រូវបានបដិសេធ។ សូមបើកវាក្នុងការកំណត់កម្មវិធីដើម្បីប្រើការថតជាសម្លេង។',
    'micPermissionRestricted': 'ការអនុញ្ញាតត្រូវបានដាក់កម្រិត',
    'micPermissionRestrictedMessage': 'ការទទួលបានដំណើរការមីក្រូហ្វូនត្រូវបានដាក់កម្រិតលើឧបករណ៍នេះ។',
    'micPermissionError': 'កំហុស',
    'micPermissionErrorMessage': 'បរាជ័យក្នុងការស្នើការអនុញ្ញាតមីក្រូហ្វូន',
    'channelInfoTitle': 'ព័ត៌មានលម្អិតឆានែល',
    'channelName': 'ឈ្មោះឆានែល',
    'channelId': 'លេខសម្គាល់ឆានែល',
    'userInfoTitle': 'ព័ត៌មានលម្អិតរបស់អ្នក',
    'userId': 'លេខសម្គាល់របស់អ្នក',
    'userName': 'ឈ្មោះរបស់អ្នក',
    'actionsTitle': 'សកម្មភាព',
    'changeThemeMenuItem': 'ផ្លាស់ប្តូរតែមសារ',
    'chatThemeDialogTitle': 'ផ្លាស់ប្តូរតែមសារ',
    'chatThemeRed': 'តែមក្រហម',
    'chatThemeBlue': 'តែមខៀវ',
    'chatThemeGreen': 'តែមបៃតង',
    'clearCacheMenuTitle': 'លុបcache និងឯកសារដែលបានទាញយក',
    'clearCacheDialogTitle': 'លុបcache និងឯកសារដែលបានទាញយក',
    'clearCacheDialogContent': 'ការលុបឯកសារដែលបានរក្សាទុកនេះមិនអាចត្រឡប់វិញបានទេ!',
    'cacheCleared': 'cache បានលុប',
    'cacheClaredMessage': 'ឯកសារដែលបានទាញយកត្រូវបានលុបចេញរួចហើយ',
    'clearCacheError': 'កំហុស',
    'clearCacheErrorPrefix': 'បរាជ័យក្នុងការលុបcache: ',
    'media': 'រូបភាព និងវីដេអូ',
    'files': 'ឯកសារ',
    'members': 'សមាជិក',
    'loadOlder': 'ផ្ទុកសារចាស់ៗ',
    'noMedia': 'មិនទាន់មានរូបភាព ឬវីដេអូទេ',
    'noFiles': 'មិនទាន់មានឯកសារទេ',
    'noMembers': 'មិនមានសមាជិកដើម្បីបង្ហាញទេ',
    'you': 'អ្នក',
    'title': 'សារ',
    'conversations': 'ការជជែក',
    'newChat': 'ជជែកថ្មី',
    'noConversations': 'មិនទាន់មានការជជែកទេ',
    'chooseTopic': 'តើអ្នកចង់ជជែកអំពីអ្វី?',
    'noTopics': 'មិនមានប្រធានបទជជែកទេ។',
    'confirmStart': 'ចាប់ផ្តើមជជែក? អ្នកទាំងអស់ក្នុងការជជែកនឹងទទួលបានការជូនដំណឹង។',
    'yes': 'បាទ/ចាស',
    'no': 'ទេ',
    'ok': 'យល់ព្រម',
    'openFailed': 'មិនអាចបើកការជជែកបានទេ។ សូមព្យាយាមម្តងទៀត។',
    'whichOne': 'សូមប្រាប់យើងថាមួយណា',
    'or': 'ឬ',
    'find': 'ស្វែងរក',
    'noMatch': 'រកមិនឃើញ។ សូមពិនិត្យព័ត៌មានដែលបានបញ្ចូល។',
    'pickOne': 'មួយណា?',
    'fillOneGroup': 'សូមបំពេញជម្រើសណាមួយ។',
  },
};
